# Config file for an example Majora's Mask: Recompiled mod.

# Fields that end up in the mod's manifest.
[manifest]

# Unique ID of this mod. Pick something long enough that it'll never be the same as any other mod.
# The name displayed in the mod management menu is separate from this so this doesn't need to be human readable.
id = "Forms_Use_More_Items"

# Version of this mod.
version = "2.0.2"

# The name that will show up for this mod in the mod menu. This should be human readable.
display_name = "Forms Use More Items"

# The description that will show up when this mod is displayed in the mod menu. This should be human readable.
description =  """Enables Link's transformation to use more items than they normally can.

Deku Link:

* Deku Sticks
* Magic Beans
* Great Fairy Sword

Goron Link:

* Bombs
* Bombchus
* Deku Nuts
* Magic Beans

Zora Link:

* Bombs
* Bombchus
* Deku Sticks
* Deku Nuts
* Magic Beans
* Bow (and Magic Arrows)
* Hookshot

Special thanks to Reonu for creating and implementing the assets for Zora Link to use the Bow and Hookshot! This update wouldn't have happened without him!

Additional thanks to ProxyMM for the `ObjDepLoader` library (and for helping us troubleshoot all the crashes we were having).
"""

# A short description that will show up in this mod's entry in the mod list. This should be human readable and kept short
# to prevent it from being cut off due to the limited space.
short_description = "Allows Link's transformation to use a few more items than they normally can."

# Authors of this mod.
authors = [ "LT_Schmiddy", "Reonu" ]

# ID of the target recomp game.
game_id = "mm"

# Minimum version of the target recomp (e.g. Zelda 64: Recompiled) that this mod can run on.
minimum_recomp_version = "1.2.0"

# Dependency mods. Each entry is the mod's ID and then an optional minimum version of the dependency mod.
dependencies = [
    "ProxyMM_ObjDepLoader:0.0.3",
    "MM_EZ_Text_Replacer_API:2.0.0"
]

# Native libraries (e.g. DLLs) and the functions they export.
native_libraries = [
# Example native library:
#    { name = "my_native_library", funcs = ["my_native_library_function"] }
]

# Inputs to the mod tool.
[inputs]

# Input elf file to generate a mod from.
elf_path = "build/mod.elf"

# Reference symbol files.
func_reference_syms_file = "Zelda64RecompSyms/mm.us.rev1.syms.toml"
data_reference_syms_files = [ "Zelda64RecompSyms/mm.us.rev1.datasyms.toml", "Zelda64RecompSyms/mm.us.rev1.datasyms_static.toml" ]

mod_filename = "mm_forms_use_more_items"

# Additional files to include in the mod.
additional_files = [
    "thumb.dds"
]
